name: Go-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag daluto/go-cicd:latest
      
    - name: Docker Push
      run: docker push daluto/go-cicd --all-tags

  deploy:
    needs : build 
    runs-on: ubuntu-latest
    name: deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A      
    - name: Deploy to minikube
      run: |
        kubectl create namespaces ci-cd &&
        kubectl apply -f Manifests/deployment.yml &&
        kubectl apply -f Manifests/deployment.yml
    - name: Get Services
      run: |
        minikube get svc -n ci-cd        
