name: Go-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag daluto/go-cicd:latest
      
    - name: Docker Push
      run: docker push daluto/go-cicd --all-tags

  deploy:

    needs : build 

    runs-on: ubuntu-latest

    name: deploy to minikube

    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Check the cluster
      run: kubectl get pods -A      
    - name: Deploy to minikube
      run: |
        kubectl apply -f Manifests/ns.yml &&
        kubectl apply -f Manifests/service.yml &&
        kubectl apply -f Manifests/deployment.yml
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'
    - name: Get Services and pods
      run: |
        kubectl get namespaces &&
        kubectl get svc -n ci-cd &&
        kubectl get pods -n ci-cd 
